platform :ios, '11.0'

target 'QRScannerApp' do

    project 'QRScannerApp.xcodeproj'
    pod 'React', :path => '../node_modules/react-native'
    pod 'React-Core', :path => '../node_modules/react-native'
    pod 'React-RCTText', :path => '../node_modules/react-native'
    pod 'React-RCTImage', :path => '../node_modules/react-native'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native'
    pod 'React-RCTWebSocket', :path => '../node_modules/react-native'
    pod 'React-CoreModules', :path => '../node_modules/react-native'
    pod 'RCTTypeSafety', :path => '../node_modules/react-native'
    pod 'React', :path => '../node_modules/react-native'
end